### ISSUE TITLE
Error message on Ubuntu 17.10

### ISSUE THREAD

**Issue by emamut** [t413/zsh-background-notify#22]
Hi there,
In Ubuntu 17.10 this error message is appearing when finishing a task with the active terminal

![image](https://user-images.githubusercontent.com/134828/32370529-71aa3d24-c05b-11e7-8632-3d8b850c6a02.png)

**Comment by rvangsgaard** [comment]
I fixed it by quoting the currentWindowId, changing this line
```
    if [ $(currentWindowId) != "$bgnotify_windowid" ]; then
```
to
```
    if [ "$(currentWindowId)" != "$bgnotify_windowid" ]; then
```

I would like to take tabs into consideration, as currently I got no notification if a long running process finishes in tab1 while I work in tab2 of the same window. Actually I get no notification if I work in another terminal, it gets the same windowId.
